# Generated by Django 3.2.12 on 2022-07-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_exemplo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prince',
            new_name='price',
        ),
    ]
